language: python

services:
    - docker

addons:
    sauce_connect:
        username:
            secure: "tCYSU/673IJ0LC7qdEk6yVtojB8GhkyJLIO1e5yeRgo/rhNE1vzh33luo2xGmaV/oFY8nhK6NJotnVB366nrDS4JrrsKrcXNqodNTnorTP2UVN+4Ggl533pypLnuXRDKcJQGWHaqAtO4zfvynOiJxemsKIucJcY3SWfGP7dJEeRhOnc3WNuq8tztTiyRo6AfsKyDMPN90AEgUbMXPBB62LsTvKbfHjNKoKXPN+8gl4+PVjeNifSXp6u1daThdBtIdAtazQqdaJKS8hEACsra0s3zvp+scSQSlEl0qZYz18bb9lpGJr+rUIIqbWKA3m+aZwcMjmwjiUCPvaF/FgsPLFNKVKM44o+7hX2tFjth/zMA/IfWRfd0agkTVC9d0E+qfphN23sE0VM3qOz24Z2ZuQWzh47KbxWHUIxvaJakBh1H5M+qngc0dmjx3IuJ224FG3ujUkdwOfazLLW28RdZ/pZJnNZr0TYS/69C0M4a013AzS8m0FAmeMr3j77OAE9DvgDdwF6zRdZlSdeh4qqwBNSEXUCADP4jVJUK4dQedkvX1VWQhaKrF1OaZnSp7dTdIfE9Y4sK0JmdFRnn28Sr8ccZ5YL0zl8xpHVfdn4sxq29QSJILdiM4M3v261Kdd236p4MxKCkhTUWhLWV5hVuRGx327tuxNSdLbHpoXKDLZE="
        access_key:
           secure: "tjWSHomShYoJCol3YhMxkWCgJL6j54xzCyrOHYXrhJUedU/0JioTEc6Zbu1iqD46zpXRfIxFXPto8mMi68Awz6SPmRJyQV29pVzYGEBVITRIpyX1qdXC048LMKAeAUfdOsaukDdR24v3uwSABWRBsygKSBKhX5PWju3rQh4E9TFwBx0WEXJHF0WsTyQFbh2SgA/sdjDkXxQYUETpTGZTAO+uZhDRr6rn8iO7iKCYRm5rrBhWvoIqE1Cir8BaIJZvsSHBsOWQ+skIiQKD48wvGSW5okqUnKjXIx4za5D6FpMFnRVRhGtlShTw40ZyETVM7+ywOXSH5S3G+1KatO3zZ8j2l3EKG1Nk14LojZ1Y4c0Jp/PxYIrILDE6kn/e1n+oqM04A1rzFJL/BLH9qvuXDUOQsqPRaa9UH3qFIOqw4A23ftsHYRu0GWlGGQvFa5BFEjv8cFgSJ6E1wl2cQRmhP8J661hNrT/wcxzE4KhboYz3+kmtctG34dTQbGngnd4bU8WMpxvi+DP3tdCokjl8HGeALPaw4y3jo9Xqw40yvNsV0qa8NtlNocN7qYI2taiSr+ehabfjZvUkxojOSvezhGbEuq5nR+eYjEjiEjAWk6iYNAd07nNNgOQQNXZFVLmAYcqvdmcgpDCtbD/okdnyxkfEaqr+U7h0ItOCN0wJq78="

python: 
    - "3.3"
    - "3.4"

before_install:
    - "pip install -r py_dependencies.txt"
    
install:
    - "./tests/travis-setup.sh"

before_script:
    - "docker start postgres"
    - "./run"

script: 
    - "./tests/tests.py"
