language: python

services:
    - docker

addons:
    sauce_connect:
        username:
            secure: "LlwTCNBd5cxYqyBOfxDBtg47zjnttVqHSGGYmlnKhMIR33myEGhEX2/SWKHFnGNerk2ShH75StLwMi4grdrgDcNe1/j7FsFSf4VGz59Lby+8UXaQc6F7z/+J925FNmHfduVs2dT9kwffkl+JWuReQkopYYQCj/NHwUHjLKwobCQeiu7K29NXG7funhYSfGsT9iojLrIC5B09LYUf/4dj8Sp/5BeSC7RyXMWwa9icurOUt911hKRs5Gxi/yKqvMSKD1IDCieOaMJ3XFNHXHlFQhxK0SfDsCsRfI7bUp6Z15tyHjWlzlUFSGc/7oQ1MNzaXF0JDkPpxr5FHp+5B+0iXYMu+EpkDAGwjzT6h6wIZxEx+07IjExHHyGqwN+aJAUFjCFs8ZTFUJN7wqL5nxKyiNdgY/VNjjjJNSRt3is5VDQ6oXd6QnyFBUMsMcYMW10JnfFXW9RJUgzxInWrUBsw4xJ4dYWfbwHJAF0OmbkFY3C5BfBiE6m58if98fE52Qb9tjHpOtH/2iJvq/Jc0JE0m2zK3ajbJB9EO95TuCWwYegXgTTPGocW8EA5VbaOiwwiaFqT6ZFmyjaMgIcOE7lsJtvzhMgnwQS9TNrDgRf19u4nzwNlsjw8S+in0Wu0jd4DlxXI0iTf5HPycV6AEwtIZKLOj4s5DytnXA2xbW4rZuQ="
        access_key:
           secure: "wRgBGFgxSRAWiQRDV+qo3T9OcIDKBxpPwhXwEZq5qswPUh8+MUZvQ1TJRjD0yT7msw4IgA2Z1I20EkGTmkJ2P68kkCWHMxT96K/apyLTyX9/ffD6FcXrSzPSHvnZao0cH2R6TU/xB10/euMKXlFZVHBNh6ohmlobZONJv2XIJTcEaAfmFrAJyBhYCDLYyYlsCZkQX/kvKdJ8VVJS5Yz7OOFZyi0YKTkXVIQGETrxQVZrNqvrd2Sj3KBNywFAtMdqSXsWHj2+lOSYNsTZcyffSP9eGuOMpKSKvs2Uub//fXZq136z5Xaj+PMn1vYvtb1GqPdowiopda9d2lROHDpfubkiT8P6yHOKZPacfO/n9gr0ZqFE+l6eeCN9nydvvqubwmmZiVGx49oT0T4r9/p4eGxeGBbVVftqSO3pIpoxZBmu/p/sMiw2ABi6Z3TfW37Ryi6fT9WMfX6e3xUjZknHaEWF6g1G1++FLUVDOS1+R9PwI3+MQnm+nmKMd+fjGR5nagxlDbeIFMQNtO/qrSlJW0PsFgFTDSQ9b2inVxvxdwL+WXfLNSY3MN4q2B246728ZxCHwLJ2vwbulFXNF43xlGPQxachXQDHHouKQv8apAUpgaXphxcEgIqPYsyjPCZSo84rQXJVHi/JTNIeWgxKw9AYIOZA/wFJ42q8VnMb8I4="

python: 
    - "3.2"
    - "3.3"
    - "3.4"

before_install:
    - "./tests/travis-setup.sh"

install:
    - "pip install -r py_dependencies.txt"

before_script:
    - "docker start postgres"
    - "./run"

script: 
    - "./tests.py"
