sudo: false

language: python

python: 
    - "3.3"
    - "3.4"

addons:
    postgresql: "9.4"
    sauce_connect:
        username:
            secure: "uM1EHGkGf/IZbdy0C5jZgjTnQBckE4NIe1xa7OVLnS8NveTodkNn49paT1mGUn7VVfP/1INfS/sBoFNsaCyunPShr5skserqQgsBm2zN2gzfaNco3ruUF22HXIYAL08IDXxpkJd2FWy02kbZD0oYKOyLdTJDZCweIAt4y5OuC0u9CmBDik5mMrLh+XcZl1wg8j69z4cdnfi5x4XD31B4sPDLFMjIE2szPZr9IYWfzhTaakPoLb9P1eHkIvTnGH72+Bv5Wj3miiBSR9wvyhKK24hlqdIehY1UMZJiaTmwGMxwHpF9SfFqlp1iFAuuuWchm8yPmYffxoh2nIdUn3BdLrQ/M/hkD3q+/49FAW7+FjjpjdD6CaLheD9kmrWjALkkaOY71gqIVCRs9pMJ389RhyFPKu0IAnhMYzWvprbuZ0W5FV7z2P8pvppXr9tvDMgHmLJLlIAFqERI1rs5l8wgdMMJeuROvJSmzjNy2s1jWC8PtPo1pOJizwtgj9mVCHx6Ss8lzV6f2J1qAemHFrWAktLZXdL4y5mkNd56iZmdxX+iBRbiHTwBnYWTfFPTy+xWmJ8XSZvULdnuhNg+TrnhkCcSn2u2XAOygW2siLqofyID0KFPHyv1FObsCRLf6Qn+dtZ6xGUCFpPR76rko46mos4x/Djva9l6q15erY7Kc78="
        access_key:
           secure: "Gc/0MEtlkzMD+2HiImOaB1YQULDjpowVQZkhLYflouvaJXZfk+1D81l52TwrCzJLXUS6hzT83l8rbeCLH9ixILNv2+iC91zlptM8cLpq24GwvqsoX4vJvZOPHrPJXcvqbrn/zn+esWu7woHfCiGhZz0U3sYU1beOz1xDAOwB1PGuhrX7eR7l9OmxJjNZYevD4acOK7U2ITXiF/bwCGflDGXsL/gloexyn0ttKN6LYSltCUjA9j+1RfC3tOkfas7CYNFzaihMdaDONpEcOilh8N/n7NQ4G0y/JGA/kv7No1GubcgLkUlix2Xu9NosVWLPkeRahghXFvuRyTaYUoz3tGTRJj6s2whVEXnsZI0Za9fhCcoqy4fbsxn2qx6p8LZsXJsjgGUKl92gO7RawmfWdBRqCKVWDbAeH2J1xSG2YNhFokhsWgrUEmAfXdhtkXQP2/BeweH6mob5Fm0DJBMJVYiv3Z8j4f2cioJ5xzinO3Ht3rUKsuHxuTn+xlZD9CZVQF8BBkBn4yb0FTzDNtEoAWR0PxfCXUUa5n2UM3XObMV9gNbfPBsgTWG9xJQ6mJ+aAity8iv4rp+irXVGiMx4KCiIpXBMUmFiSuc26LygxFYX5T/bDX3z0OfKcaSS1B24GhU3sFjuVKzcUMieK/MLFmQxQ9d41iypYXwfs2/iqrk="

before_install:
    - "pip install -r py_dependencies.txt"
    - "psql -c 'CREATE DATABASE blog'"
    - "mkdir configs"
    - "echo '{\"connection_string\": \"postgresql://postgres@127.0.0.1:5432/blog\"}' > configs/database.json"
    - "echo '{\"display_full_name\": true}' > configs/templates.json"

install:
    - "cd $TRAVIS_BUILD_DIR/tests"
    - "python3 ./travis-setup.py"

before_script:
    - "$TRAVIS_BUILD_DIR/run &"

script: 
    - "python3 $TRAVIS_BUILD_DIR/tests/tests.py"
