language: python

services:
    - docker

addons:
    sauce_connect:
        username:
            secure: "LlwTCNBd5cxYqyBOfxDBtg47zjnttVqHSGGYmlnKhMIR33myEGhEX2/SWKHFnGNerk2ShH75StLwMi4grdrgDcNe1/j7FsFSf4VGz59Lby+8UXaQc6F7z/+J925FNmHfduVs2dT9kwffkl+JWuReQkopYYQCj/NHwUHjLKwobCQeiu7K29NXG7funhYSfGsT9iojLrIC5B09LYUf/4dj8Sp/5BeSC7RyXMWwa9icurOUt911hKRs5Gxi/yKqvMSKD1IDCieOaMJ3XFNHXHlFQhxK0SfDsCsRfI7bUp6Z15tyHjWlzlUFSGc/7oQ1MNzaXF0JDkPpxr5FHp+5B+0iXYMu+EpkDAGwjzT6h6wIZxEx+07IjExHHyGqwN+aJAUFjCFs8ZTFUJN7wqL5nxKyiNdgY/VNjjjJNSRt3is5VDQ6oXd6QnyFBUMsMcYMW10JnfFXW9RJUgzxInWrUBsw4xJ4dYWfbwHJAF0OmbkFY3C5BfBiE6m58if98fE52Qb9tjHpOtH/2iJvq/Jc0JE0m2zK3ajbJB9EO95TuCWwYegXgTTPGocW8EA5VbaOiwwiaFqT6ZFmyjaMgIcOE7lsJtvzhMgnwQS9TNrDgRf19u4nzwNlsjw8S+in0Wu0jd4DlxXI0iTf5HPycV6AEwtIZKLOj4s5DytnXA2xbW4rZuQ="
        access_key:
           secure: "SK8R5xcUDe2XwQ0J1QodQhUVxFxBaQZRlUJOZbl6jPVYZRDlP/KUFLzfmqWvE6sLTZPAQueW8bQwyz/567JCdXldHozRuxM55lH1gj9uOGyS9LQySZhgr6gjXXy+U52in+TYtNQaiSmnj2B+ti7rxIwEuUqyHcoS4ACzv6AbuILMlsMXTd3RC1kbxfwHoOXOM1d4FK/CVYZk2H0huRtsUOkoEGE7rGvmU1laTuhA0FfATPfM7DB/+TnvhXVNLBs8lIXj1E9WEnFcPiiFpBLtMTX1SvP3a/lHWkFmB37cU0c/YWzHTpPRitp1QLaA+Cau1YNadO8hj/4w8Gq8tn3UNpRJfmEpue6DbqV3f0QOdXIwnREO7IGXGZn/TD7lqeDI8SOqd1iRtc0+NrwWwoALx33Hh3LdjmmfqUCngHPUIBkEByEWLk5na+U++f06f7ebGxlXLaozFggVQi+fGEcz6pm7nIlWc7pKq2bIA4i78zU0bivHfM80qEBNzhxIe7E26fwoP4dJG8LkFK3JokCEgupBpnkWIAuf6/gb1PyGjhP/4cDWW3ZKpNCzO5Ql8wbwQFJr0eeJc4mf8cu7yOyzNlZGazWLh2Tq+gLxh7Pqbbvep7YKgZ5hhhchVLd/9fWvydj8UsCZyKfGA4BRXVDwKxrXa0Wc68hknlAEp1GNCas="

python: 
    - "3.2"
    - "3.3"
    - "3.4"

before_install:
    - "./tests/travis-setup.sh"

install:
    - "pip install -r py_dependencies.py"

before_script:
    - "docker start postgres"
    - "./run"

script: 
    - "./tests.py"
