#!/usr/bin/env python3
import timpani 
from timpani import configmanager
import atexit

configs = configmanager.ConfigManager()
webserverConfig = configs["webserver"]

if __name__ == "__main__":
	timpani.wsgi.application.run(host = webserverConfig["host"], port = webserverConfig["port"])
